version: '3.5'

services:
  account-service:
    build:
        context: ./
        dockerfile: Dockerfile
    restart: unless-stopped
    container_name: account-service
    image: account-service
    ports:
      - "8081:8081"
    environment:
#      - SPRING_DATASOURCE_URL=jdbc:mysql://mysql_8_0_30:3306/microservices?createDatabaseIfNotExist=true&characterEncoding=UTF-8&serverTimeZone=UTC
#      - SPRING_DATASOURCE_USERNAME=vuhso04
#      - SPRING_DATASOURCE_PASSWORD=123abc
#      - SPRING_APPLICATION_NAME=account-service
#      - EUREKA_CLIENT_SERVICE_URL_DEFAULTZONE=http://localhost:8761/eureka
      - SPRING_CLOUD_CONFIG_URI=http://config-server:8762/
    networks:
      - vuhso-microservices
networks:
    vuhso-microservices:
        external: true